-- =============================================================================
-- V1 · Initial schema (the model as it was before Flyway was introduced).
--
-- Existing databases created by Hibernate's ddl-auto are *baselined* at this
-- version (spring.flyway.baseline-on-migrate), so this script only runs on
-- fresh databases. Every later change lives in V2+.
-- Portable SQL: PostgreSQL (production) and H2 in PostgreSQL mode (tests/local).
-- =============================================================================

CREATE TABLE IF NOT EXISTS users (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    role      VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('TRAINER', 'CLIENT'))
);

CREATE TABLE IF NOT EXISTS clients (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    first_name   VARCHAR(255) NOT NULL,
    last_name    VARCHAR(255) NOT NULL,
    phone        VARCHAR(255),
    objective    VARCHAR(255),
    birth_date   DATE,
    notes        TEXT,
    trainer_id   BIGINT,
    photo_base64 TEXT,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_clients_user UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS plans (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL,
    description           VARCHAR(1000),
    monthly_price         NUMERIC(8, 2) NOT NULL,
    review_frequency_days INTEGER NOT NULL,
    messaging_enabled     BOOLEAN NOT NULL,
    analytics_enabled     BOOLEAN NOT NULL,
    pdf_export_enabled    BOOLEAN NOT NULL,
    priority_support      BOOLEAN NOT NULL,
    active                BOOLEAN NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    BIGINT NOT NULL,
    plan_id      BIGINT NOT NULL,
    start_date   DATE NOT NULL,
    end_date     DATE,
    renewal_date DATE NOT NULL,
    status       VARCHAR(20) NOT NULL,
    active       BOOLEAN DEFAULT TRUE NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES plans (id),
    CONSTRAINT ck_subscriptions_status CHECK (status IN ('ACTIVE', 'PAUSED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS weekly_reports (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id          BIGINT NOT NULL,
    weight             NUMERIC(5, 2) NOT NULL,
    waist              NUMERIC(5, 2),
    body_fat           NUMERIC(4, 1),
    energy_level       INTEGER,
    diet_adherence     INTEGER,
    training_adherence INTEGER,
    comments           VARCHAR(1000),
    coach_feedback     VARCHAR(1000),
    status             VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    reviewed_at        TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_weekly_reports_client FOREIGN KEY (client_id) REFERENCES clients (id)
);

CREATE TABLE IF NOT EXISTS workouts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(2000),
    objective     VARCHAR(500),
    days_per_week INTEGER,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS workout_exercises (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id    BIGINT NOT NULL,
    exercise_name VARCHAR(255) NOT NULL,
    sets          INTEGER NOT NULL,
    reps          INTEGER,
    rir           INTEGER,
    rest_seconds  INTEGER,
    notes         VARCHAR(1000),
    order_index   INTEGER NOT NULL,
    day_number    INTEGER,
    day_name      VARCHAR(100),
    warm_up_sets  VARCHAR(50),
    approx_reps   VARCHAR(50),
    CONSTRAINT fk_workout_exercises_workout FOREIGN KEY (workout_id) REFERENCES workouts (id)
);

CREATE TABLE IF NOT EXISTS client_workouts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT NOT NULL,
    workout_id  BIGINT NOT NULL,
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date    DATE,
    active      BOOLEAN NOT NULL,
    CONSTRAINT fk_client_workouts_workout FOREIGN KEY (workout_id) REFERENCES workouts (id)
);

CREATE TABLE IF NOT EXISTS diets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    objective   VARCHAR(200),
    active      BOOLEAN DEFAULT TRUE NOT NULL,
    trainer_id  BIGINT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_diets_trainer_id ON diets (trainer_id);

CREATE TABLE IF NOT EXISTS diet_days (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diet_id     BIGINT NOT NULL,
    name        VARCHAR(200) NOT NULL,
    day_number  INTEGER,
    notes       VARCHAR(1000),
    order_index INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT diet_days_diet_id_fkey FOREIGN KEY (diet_id) REFERENCES diets (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_diet_days_diet_id ON diet_days (diet_id);

CREATE TABLE IF NOT EXISTS diet_meals (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diet_day_id BIGINT NOT NULL,
    name        VARCHAR(200) NOT NULL,
    time        VARCHAR(50),
    notes       VARCHAR(1000),
    order_index INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT diet_meals_diet_day_id_fkey FOREIGN KEY (diet_day_id) REFERENCES diet_days (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_diet_meals_day_id ON diet_meals (diet_day_id);

CREATE TABLE IF NOT EXISTS diet_foods (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diet_meal_id  BIGINT NOT NULL,
    food_name     VARCHAR(200) NOT NULL,
    quantity      NUMERIC(8, 2),
    unit          VARCHAR(50),
    calories      NUMERIC(7, 2),
    protein_grams NUMERIC(6, 2),
    carbs_grams   NUMERIC(6, 2),
    fat_grams     NUMERIC(6, 2),
    notes         VARCHAR(500),
    order_index   INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT diet_foods_diet_meal_id_fkey FOREIGN KEY (diet_meal_id) REFERENCES diet_meals (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_diet_foods_meal_id ON diet_foods (diet_meal_id);

CREATE TABLE IF NOT EXISTS diet_alternatives (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diet_food_id     BIGINT NOT NULL,
    alternative_name VARCHAR(200) NOT NULL,
    quantity         NUMERIC(8, 2),
    unit             VARCHAR(50),
    notes            VARCHAR(500),
    order_index      INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT diet_alternatives_diet_food_id_fkey FOREIGN KEY (diet_food_id) REFERENCES diet_foods (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_diet_alternatives_food_id ON diet_alternatives (diet_food_id);

CREATE TABLE IF NOT EXISTS client_diets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     BIGINT NOT NULL,
    diet_id       BIGINT NOT NULL,
    assigned_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    start_date    DATE,
    end_date      DATE,
    active        BOOLEAN DEFAULT TRUE NOT NULL,
    trainer_notes VARCHAR(1000),
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT client_diets_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT client_diets_diet_id_fkey FOREIGN KEY (diet_id) REFERENCES diets (id)
);
CREATE INDEX IF NOT EXISTS idx_client_diets_client_id ON client_diets (client_id);
CREATE INDEX IF NOT EXISTS idx_client_diets_diet_id ON client_diets (diet_id);
CREATE INDEX IF NOT EXISTS idx_client_diets_active ON client_diets (active);

CREATE TABLE IF NOT EXISTS client_analyses (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id             BIGINT NOT NULL,
    title                 VARCHAR(300) NOT NULL,
    analysis_date         DATE NOT NULL,
    client_comment        VARCHAR(2000),
    trainer_internal_note VARCHAR(2000),
    original_file_name    VARCHAR(500) NOT NULL,
    stored_file_name      VARCHAR(500) NOT NULL,
    storage_key           VARCHAR(1000) NOT NULL,
    content_type          VARCHAR(100) NOT NULL,
    file_size             BIGINT NOT NULL,
    storage_provider      VARCHAR(20) NOT NULL,
    uploaded_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    reviewed_at           TIMESTAMP WITH TIME ZONE,
    reviewed_by_user_id   BIGINT,
    status                VARCHAR(20) NOT NULL,
    active                BOOLEAN NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_client_analyses_status CHECK (status IN ('UPLOADED', 'REVIEWED'))
);
