-- =============================================================================
-- V2 · Schema review + new modules.
--
-- Written to be safe both on a fresh database (after V1) and on a database
-- that was previously managed by Hibernate ddl-auto=update (baselined at V1),
-- hence the IF EXISTS / IF NOT EXISTS guards.
-- Portable SQL: PostgreSQL and H2 (PostgreSQL mode).
-- =============================================================================

-- ─── 1. Drift left behind by ddl-auto=update ─────────────────────────────────

-- An old version of the model mapped one subscription per client. That unique
-- constraint makes it impossible to keep the subscription history (changing
-- plan failed). "One current subscription per client" is enforced in V3.
ALTER TABLE subscriptions DROP CONSTRAINT IF EXISTS ukri12po99qh9nqs36pueuqg7kv;

-- Orphan column no longer mapped by the model (client state = its subscription).
ALTER TABLE clients DROP COLUMN IF EXISTS status;

-- ─── 2. New columns ──────────────────────────────────────────────────────────

ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS cancel_at_period_end BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP WITH TIME ZONE;

-- Subscriptions are now billed monthly; renewal_date used to be computed with
-- the review frequency (e.g. +7 days). Move current ones to start + 1 month.
UPDATE subscriptions
   SET renewal_date = start_date + INTERVAL '1' MONTH
 WHERE active = TRUE
   AND status = 'ACTIVE'
   AND renewal_date < start_date + INTERVAL '1' MONTH;

-- ─── 3. Referential integrity for existing tables ────────────────────────────

-- Rows pointing to entities that no longer exist would block the new FKs.
DELETE FROM subscriptions WHERE client_id NOT IN (SELECT id FROM clients);
DELETE FROM client_workouts WHERE client_id NOT IN (SELECT id FROM clients);
DELETE FROM client_analyses WHERE client_id NOT IN (SELECT id FROM clients);
UPDATE client_analyses SET reviewed_by_user_id = NULL
 WHERE reviewed_by_user_id IS NOT NULL AND reviewed_by_user_id NOT IN (SELECT id FROM users);

ALTER TABLE clients
    ADD CONSTRAINT fk_clients_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE subscriptions
    ADD CONSTRAINT fk_subscriptions_client FOREIGN KEY (client_id) REFERENCES clients (id);
ALTER TABLE client_workouts
    ADD CONSTRAINT fk_client_workouts_client FOREIGN KEY (client_id) REFERENCES clients (id);
ALTER TABLE client_analyses
    ADD CONSTRAINT fk_client_analyses_client FOREIGN KEY (client_id) REFERENCES clients (id);
ALTER TABLE client_analyses
    ADD CONSTRAINT fk_client_analyses_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users (id);

-- PostgreSQL does not index foreign keys automatically.
CREATE INDEX IF NOT EXISTS idx_subscriptions_client ON subscriptions (client_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_plan ON subscriptions (plan_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status_renewal ON subscriptions (status, renewal_date);
CREATE INDEX IF NOT EXISTS idx_weekly_reports_client_created ON weekly_reports (client_id, created_at);
CREATE INDEX IF NOT EXISTS idx_weekly_reports_status ON weekly_reports (status);
CREATE INDEX IF NOT EXISTS idx_client_workouts_client ON client_workouts (client_id);
CREATE INDEX IF NOT EXISTS idx_client_workouts_workout ON client_workouts (workout_id);
CREATE INDEX IF NOT EXISTS idx_workout_exercises_workout ON workout_exercises (workout_id);
CREATE INDEX IF NOT EXISTS idx_client_analyses_client ON client_analyses (client_id);

-- ─── 4. New modules ──────────────────────────────────────────────────────────

-- Email outbox: every email generated by the platform (test mode = never sent).
CREATE TABLE IF NOT EXISTS email_messages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     BIGINT,
    to_address    VARCHAR(320) NOT NULL,
    to_name       VARCHAR(200),
    subject       VARCHAR(300) NOT NULL,
    html_body     TEXT NOT NULL,
    type          VARCHAR(30) NOT NULL,
    status        VARCHAR(20) NOT NULL,
    mode          VARCHAR(10) NOT NULL,
    error_message VARCHAR(1000),
    sent_at       TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_email_messages_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_email_messages_client ON email_messages (client_id);
CREATE INDEX IF NOT EXISTS idx_email_messages_created ON email_messages (created_at);

-- Charges. Card data is never stored beyond brand + last 4 digits.
CREATE TABLE IF NOT EXISTS payments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             BIGINT,
    client_id           BIGINT NOT NULL,
    subscription_id     BIGINT,
    concept             VARCHAR(300) NOT NULL,
    amount              NUMERIC(10, 2) NOT NULL,
    currency            VARCHAR(3) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    method              VARCHAR(20),
    due_date            DATE NOT NULL,
    period_start        DATE,
    period_end          DATE,
    paid_at             TIMESTAMP WITH TIME ZONE,
    refunded_at         TIMESTAMP WITH TIME ZONE,
    provider_reference  VARCHAR(100),
    card_brand          VARCHAR(20),
    card_last4          VARCHAR(4),
    bizum_phone         VARCHAR(20),
    failed_attempts     INTEGER DEFAULT 0 NOT NULL,
    last_failure_reason VARCHAR(300),
    last_attempt_at     TIMESTAMP WITH TIME ZONE,
    trainer_notes       VARCHAR(500),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_payments_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_payments_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE SET NULL,
    CONSTRAINT ck_payments_amount CHECK (amount > 0),
    CONSTRAINT ck_payments_status CHECK (status IN ('PENDING', 'PAID', 'REFUNDED', 'CANCELLED')),
    CONSTRAINT ck_payments_method CHECK (method IS NULL OR method IN ('CARD', 'BIZUM', 'CASH')),
    CONSTRAINT ck_payments_paid_has_method CHECK (status NOT IN ('PAID', 'REFUNDED') OR (method IS NOT NULL AND paid_at IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS idx_payments_client ON payments (client_id);
CREATE INDEX IF NOT EXISTS idx_payments_subscription ON payments (subscription_id);
CREATE INDEX IF NOT EXISTS idx_payments_status_due ON payments (status, due_date);
CREATE INDEX IF NOT EXISTS idx_payments_paid_at ON payments (paid_at);

-- Client ⇄ trainer chat (one conversation per client).
CREATE TABLE IF NOT EXISTS messages (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id      BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    sender_role    VARCHAR(20) NOT NULL,
    content        VARCHAR(4000) NOT NULL,
    read_at        TIMESTAMP WITH TIME ZONE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_messages_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_user_id) REFERENCES users (id),
    CONSTRAINT ck_messages_sender_role CHECK (sender_role IN ('TRAINER', 'CLIENT'))
);
CREATE INDEX IF NOT EXISTS idx_messages_client ON messages (client_id, created_at);

CREATE TABLE IF NOT EXISTS progress_photos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       BIGINT NOT NULL,
    taken_on        DATE NOT NULL,
    pose            VARCHAR(10) NOT NULL,
    notes           VARCHAR(500),
    trainer_comment VARCHAR(1000),
    storage_key     VARCHAR(500) NOT NULL,
    content_type    VARCHAR(50) NOT NULL,
    file_size       BIGINT NOT NULL,
    uploaded_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_progress_photos_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT ck_progress_photos_pose CHECK (pose IN ('FRONT', 'SIDE', 'BACK', 'OTHER'))
);
CREATE INDEX IF NOT EXISTS idx_progress_photos_client ON progress_photos (client_id, taken_on);

-- Workout log: workout/exercise names are snapshotted (no FK to workouts on
-- purpose) so the history survives when the trainer edits or deletes a routine.
CREATE TABLE IF NOT EXISTS workout_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    BIGINT NOT NULL,
    workout_id   BIGINT,
    workout_name VARCHAR(255) NOT NULL,
    day_number   INTEGER NOT NULL,
    day_name     VARCHAR(100),
    performed_on DATE NOT NULL,
    notes        VARCHAR(1000),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_workout_logs_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT uk_workout_log_day UNIQUE (client_id, performed_on, day_number)
);

CREATE TABLE IF NOT EXISTS workout_log_sets (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id         BIGINT NOT NULL,
    exercise_id    BIGINT,
    exercise_name  VARCHAR(255) NOT NULL,
    exercise_order INTEGER NOT NULL,
    set_number     INTEGER NOT NULL,
    weight_kg      NUMERIC(6, 2) NOT NULL,
    reps           INTEGER,
    rir            INTEGER NOT NULL,
    CONSTRAINT fk_workout_log_sets_log FOREIGN KEY (log_id) REFERENCES workout_logs (id) ON DELETE CASCADE,
    CONSTRAINT ck_workout_log_sets_weight CHECK (weight_kg >= 0),
    CONSTRAINT ck_workout_log_sets_rir CHECK (rir BETWEEN 0 AND 10),
    CONSTRAINT ck_workout_log_sets_set CHECK (set_number >= 1)
);
CREATE INDEX IF NOT EXISTS idx_workout_log_sets_log ON workout_log_sets (log_id);

-- Trainer to-do list and periodic reviews.
CREATE TABLE IF NOT EXISTS trainer_tasks (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(200) NOT NULL,
    description    VARCHAR(2000),
    client_id      BIGINT,
    type           VARCHAR(20) NOT NULL,
    priority       VARCHAR(10) NOT NULL,
    status         VARCHAR(10) NOT NULL,
    due_date       DATE,
    completed_at   TIMESTAMP WITH TIME ZONE,
    auto_generated BOOLEAN DEFAULT FALSE NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_trainer_tasks_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT ck_trainer_tasks_status CHECK (status IN ('PENDING', 'DONE'))
);
CREATE INDEX IF NOT EXISTS idx_trainer_tasks_client ON trainer_tasks (client_id);
CREATE INDEX IF NOT EXISTS idx_trainer_tasks_status_due ON trainer_tasks (status, due_date);

-- Public reviews: one per client, ever.
CREATE TABLE IF NOT EXISTS testimonials (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT NOT NULL,
    author_name VARCHAR(100) NOT NULL,
    plan_name   VARCHAR(100),
    rating      INTEGER NOT NULL,
    content     VARCHAR(1000) NOT NULL,
    visible     BOOLEAN DEFAULT TRUE NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_testimonials_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT uk_testimonials_client UNIQUE (client_id),
    CONSTRAINT ck_testimonials_rating CHECK (rating BETWEEN 1 AND 5)
);
CREATE INDEX IF NOT EXISTS idx_testimonials_visible ON testimonials (visible, created_at);
