-- =============================================================================
-- V5 · Web Push subscriptions (PWA notifications) and passkeys (WebAuthn).
-- Portable SQL: PostgreSQL and H2 (PostgreSQL mode).
-- =============================================================================

-- Key/value application settings (e.g. the VAPID key pair used to sign pushes).
CREATE TABLE IF NOT EXISTS app_settings (
    setting_key   VARCHAR(100) PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

-- One row per device/browser that accepted notifications.
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    endpoint        VARCHAR(1000) NOT NULL,
    p256dh          VARCHAR(200) NOT NULL,
    auth            VARCHAR(100) NOT NULL,
    user_agent      VARCHAR(300),
    failure_count   INTEGER DEFAULT 0 NOT NULL,
    last_success_at TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_push_subscriptions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_push_subscriptions_endpoint UNIQUE (endpoint)
);
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user ON push_subscriptions (user_id);

-- WebAuthn user handle: random, stable, not personally identifiable.
ALTER TABLE users ADD COLUMN IF NOT EXISTS webauthn_user_handle VARCHAR(100);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_webauthn_user_handle ON users (webauthn_user_handle);

-- Registered passkeys (Face ID, Touch ID, Windows Hello, Android fingerprint, security keys...).
CREATE TABLE IF NOT EXISTS passkey_credentials (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    credential_id   VARCHAR(1024) NOT NULL,
    public_key_cose TEXT NOT NULL,
    signature_count BIGINT DEFAULT 0 NOT NULL,
    name            VARCHAR(100) NOT NULL,
    transports      VARCHAR(200),
    backup_eligible BOOLEAN DEFAULT FALSE NOT NULL,
    backed_up       BOOLEAN DEFAULT FALSE NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_passkey_credentials_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_passkey_credentials_credential UNIQUE (credential_id)
);
CREATE INDEX IF NOT EXISTS idx_passkey_credentials_user ON passkey_credentials (user_id);
