-- =============================================================================
-- V6 · Exercise technique videos: the client records an exercise so the trainer can
-- correct the technique, and the trainer can send demonstration videos to a client.
-- Portable SQL: PostgreSQL and H2 (PostgreSQL mode).
-- =============================================================================

CREATE TABLE IF NOT EXISTS technique_videos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id         BIGINT NOT NULL,
    -- CLIENT = the client's execution to review · TRAINER = demonstration from the trainer
    source            VARCHAR(10) NOT NULL,
    exercise_name     VARCHAR(150) NOT NULL,
    note              VARCHAR(1000),
    storage_key       VARCHAR(500) NOT NULL,
    content_type      VARCHAR(50) NOT NULL,
    file_size         BIGINT NOT NULL,
    duration_seconds  INTEGER,
    feedback          VARCHAR(2000),
    reviewed_at       TIMESTAMP WITH TIME ZONE,
    -- When the client saw the trainer's video / the trainer's feedback
    client_seen_at    TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_technique_videos_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE,
    CONSTRAINT ck_technique_videos_source CHECK (source IN ('CLIENT', 'TRAINER'))
);
CREATE INDEX IF NOT EXISTS idx_technique_videos_client ON technique_videos (client_id, created_at);
CREATE INDEX IF NOT EXISTS idx_technique_videos_pending ON technique_videos (source, reviewed_at);
