-- =============================================================================
-- V7 · New client intake: contact request → questionnaire → approval → account activation.
-- Portable SQL: PostgreSQL and H2 (PostgreSQL mode).
-- =============================================================================

CREATE TABLE IF NOT EXISTS leads (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name                 VARCHAR(100) NOT NULL,
    last_name                  VARCHAR(100) NOT NULL,
    email                      VARCHAR(320) NOT NULL,
    phone                      VARCHAR(30),
    -- What the person wants to achieve (contact form)
    objective                  VARCHAR(1500) NOT NULL,
    preferred_plan_id          BIGINT,
    status                     VARCHAR(30) NOT NULL,
    -- Single-use questionnaire link: only the SHA-256 of the token is stored
    questionnaire_token_hash   VARCHAR(64),
    questionnaire_sent_at      TIMESTAMP WITH TIME ZONE,
    questionnaire_expires_at   TIMESTAMP WITH TIME ZONE,
    questionnaire_json         TEXT,
    questionnaire_completed_at TIMESTAMP WITH TIME ZONE,
    -- Private note of the trainer and the message sent with the last decision
    trainer_note               VARCHAR(2000),
    decision_message           VARCHAR(2000),
    decided_at                 TIMESTAMP WITH TIME ZONE,
    client_id                  BIGINT,
    -- GDPR: consent to be contacted (form) and explicit consent for health data (questionnaire)
    consent_at                 TIMESTAMP WITH TIME ZONE NOT NULL,
    health_consent_at          TIMESTAMP WITH TIME ZONE,
    created_at                 TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                 TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_leads_plan FOREIGN KEY (preferred_plan_id) REFERENCES plans (id) ON DELETE SET NULL,
    CONSTRAINT fk_leads_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE SET NULL,
    CONSTRAINT uk_leads_questionnaire_token UNIQUE (questionnaire_token_hash),
    CONSTRAINT ck_leads_status CHECK (status IN ('NEW', 'QUESTIONNAIRE_SENT', 'QUESTIONNAIRE_COMPLETED', 'ACCEPTED', 'REJECTED'))
);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads (status, created_at);
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads (email);
CREATE INDEX IF NOT EXISTS idx_leads_client ON leads (client_id);

-- Account activation link (the new client chooses a password): SHA-256 of the token.
ALTER TABLE users ADD COLUMN IF NOT EXISTS activation_token_hash VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS activation_expires_at TIMESTAMP WITH TIME ZONE;
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_activation_token ON users (activation_token_hash);
