package com.adrifit.backend.task.dto;

import com.adrifit.backend.task.domain.TaskPriority;
import com.adrifit.backend.task.domain.TaskStatus;
import com.adrifit.backend.task.domain.TaskType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.time.Instant;
import java.time.LocalDate;

public final class TaskDtos {

    private TaskDtos() {
    }

    public record TaskResponse(
            Long id,
            String title,
            String description,
            Long clientId,
            String clientName,
            TaskType type,
            TaskPriority priority,
            TaskStatus status,
            LocalDate dueDate,
            boolean overdue,
            boolean autoGenerated,
            Instant completedAt,
            Instant createdAt
    ) {
    }

    public record SaveTaskRequest(
            @NotBlank(message = "El título es obligatorio") @Size(max = 200) String title,
            @Size(max = 2000) String description,
            Long clientId,
            TaskType type,
            TaskPriority priority,
            LocalDate dueDate
    ) {
    }

    public enum ReviewState {
        /** The review date has passed. */
        OVERDUE,
        /** Due in the next 3 days (or today). */
        DUE_SOON,
        UPCOMING
    }

    /** Periodic review schedule of a client, derived from its plan's review frequency. */
    public record ReviewScheduleItem(
            Long clientId,
            String clientName,
            String planName,
            int frequencyDays,
            LocalDate lastReviewDate,
            LocalDate nextReviewDate,
            long daysUntil,
            ReviewState state,
            /* Latest report still waiting for the trainer's feedback, if any. */
            Long pendingReportId,
            Instant pendingReportAt
    ) {
    }
}
