export type TaskType = 'REVIEW' | 'TASK' | 'CALL' | 'PAYMENT' | 'OTHER';
export type TaskPriority = 'LOW' | 'MEDIUM' | 'HIGH';
export type TaskStatus = 'PENDING' | 'DONE';
export type ReviewState = 'OVERDUE' | 'DUE_SOON' | 'UPCOMING';

export interface TrainerTask {
  id: number;
  title: string;
  description: string | null;
  clientId: number | null;
  clientName: string | null;
  type: TaskType;
  priority: TaskPriority;
  status: TaskStatus;
  dueDate: string | null;
  overdue: boolean;
  autoGenerated: boolean;
  completedAt: string | null;
  createdAt: string;
}

export interface SaveTaskRequest {
  title: string;
  description?: string | null;
  clientId?: number | null;
  type?: TaskType;
  priority?: TaskPriority;
  dueDate?: string | null;
}

export interface ReviewScheduleItem {
  clientId: number;
  clientName: string;
  planName: string;
  frequencyDays: number;
  lastReviewDate: string | null;
  nextReviewDate: string;
  daysUntil: number;
  state: ReviewState;
  pendingReportId: number | null;
  pendingReportAt: string | null;
}

export interface DailyJobResult {
  subscriptionsProcessed: number;
  reviewTasksCreated: number;
}

export const TASK_TYPE_LABEL: Record<TaskType, string> = {
  REVIEW: 'Revisión',
  TASK: 'Tarea',
  CALL: 'Llamada',
  PAYMENT: 'Cobro',
  OTHER: 'Otro',
};

export const TASK_PRIORITY_LABEL: Record<TaskPriority, string> = {
  LOW: 'Baja',
  MEDIUM: 'Media',
  HIGH: 'Alta',
};
